name: Create Release

on: workflow_dispatch

jobs:
  release-windows:
    runs-on: windows-latest
    name: Create Windows Release
    steps:
      - name: Checkout and Clone Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      - name: Restore Projects
        run: dotnet restore
        
      - name: Build FontStashSharp Release separately
        run: dotnet publish -r win-x64 -c Release -f netstandard2.0 Brocco\FontStashSharp\src\XNA\FontStashSharp.FNA.Core.csproj
      
      - name: Build Upfall Release
        run: dotnet publish -r win-x64 -c Release -f net7.0 Upfall\Upfall.csproj
        
      - name: Copy Dependencies
        run: copy "Brocco\deps\win-x64\*.*" "Upfall\bin\Release\net7.0\win-x64\publish"
        
      - name: Compress Artifacts
        run: |
          cd "Upfall\bin\Release\net7.0\win-x64"
          tar -acvf upfall-win-x64.zip publish
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: win-x64.zip
          path: ${{ github.workspace }}\Upfall\bin\Release\net7.0\win-x64\win-x64.zip
