name: Create Release

on: workflow_dispatch

jobs:
  release-windows:
    runs-on: windows-latest
    name: Create Windows Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      - name: Build project
        run: dotnet build -r win-x64 -c Release
        
      - name: Copy dependencies
        run: copy "Brocco\deps\win-x64\*.*" "Upfall\bin\Release\net7.0\win-x64\publish"
        
      - name: Compress artifacts
        run: |
          cd "Upfall\bin\Release\net7.0\win-x64
          tar -acvf upfall-win-x64.zip publish
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: win-x64.zip
          path: ${{ github.workspace }}\Upfall\bin\Release\net7.0\win-x64\publish\win-x64.zip
